name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Build
       run : |
         touch .env
         echo << EOS >> .env
         ${{ vars.multiple_rows }}
         EOS
         cat .env
